# Generated by Django 2.2a1 on 2019-01-26 15:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20190125_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaugeboson',
            name='deletion_date',
            field=models.DateTimeField(default=datetime.datetime(2029, 1, 25, 15, 12, 56, 246070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lepton',
            name='deletion_date',
            field=models.DateTimeField(default=datetime.datetime(2029, 1, 25, 15, 12, 56, 246070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quark',
            name='deletion_date',
            field=models.DateTimeField(default=datetime.datetime(2029, 1, 25, 15, 12, 56, 246070, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scalarboson',
            name='deletion_date',
            field=models.DateTimeField(default=datetime.datetime(2029, 1, 25, 15, 12, 56, 246070, tzinfo=utc)),
        ),
    ]
