# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20180214_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaugeboson',
            name='json_field',
        ),
        migrations.RemoveField(
            model_name='lepton',
            name='json_field',
        ),
        migrations.RemoveField(
            model_name='quark',
            name='json_field',
        ),
        migrations.RemoveField(
            model_name='scalarboson',
            name='json_field',
        ),
        migrations.AddField(
            model_name='gaugeboson',
            name='_parameters',
            field=models.TextField(blank=True, db_column='parameters', default='{}', verbose_name='parameters'),
        ),
        migrations.AddField(
            model_name='lepton',
            name='_parameters',
            field=models.TextField(blank=True, db_column='parameters', default='{}', verbose_name='parameters'),
        ),
        migrations.AddField(
            model_name='quark',
            name='_parameters',
            field=models.TextField(blank=True, db_column='parameters', default='{}', verbose_name='parameters'),
        ),
        migrations.AddField(
            model_name='scalarboson',
            name='_parameters',
            field=models.TextField(blank=True, db_column='parameters', default='{}', verbose_name='parameters'),
        ),
    ]
