# Generated by Django 2.2a1 on 2019-01-28 11:59

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20190126_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('ui_name', models.CharField(max_length=200, verbose_name='name')),
                ('tenant_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name="tenant's uuid")),
                ('_parameters', models.TextField(blank=True, db_column='parameters', default='{}', verbose_name='parameters')),
                ('parameters_schema_name', models.CharField(default='Generic', max_length=200, verbose_name='jsonschema name')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('deletion_date', models.DateTimeField(default=datetime.datetime(2029, 1, 27, 11, 59, 13, 502088, tzinfo=utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='gaugeboson',
            name='deletion_date',
            field=models.DateTimeField(default=datetime.datetime(2029, 1, 27, 11, 59, 13, 502088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='lepton',
            name='deletion_date',
            field=models.DateTimeField(default=datetime.datetime(2029, 1, 27, 11, 59, 13, 502088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='quark',
            name='deletion_date',
            field=models.DateTimeField(default=datetime.datetime(2029, 1, 27, 11, 59, 13, 502088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='scalarboson',
            name='deletion_date',
            field=models.DateTimeField(default=datetime.datetime(2029, 1, 27, 11, 59, 13, 502088, tzinfo=utc)),
        ),
    ]
