# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20180214_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaugeboson',
            name='_parameters_1',
            field=models.TextField(blank=True, default='{"a": "A"}'),
        ),
        migrations.AddField(
            model_name='lepton',
            name='_parameters_1',
            field=models.TextField(blank=True, default='{"a": "A"}'),
        ),
        migrations.AddField(
            model_name='quark',
            name='_parameters_1',
            field=models.TextField(blank=True, default='{"a": "A"}'),
        ),
        migrations.AddField(
            model_name='scalarboson',
            name='_parameters_1',
            field=models.TextField(blank=True, default='{"a": "A"}'),
        ),
    ]
