# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-16 11:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_auto_20180214_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaugeboson',
            name='_parameters_1',
        ),
        migrations.RemoveField(
            model_name='lepton',
            name='_parameters_1',
        ),
        migrations.RemoveField(
            model_name='quark',
            name='_parameters_1',
        ),
        migrations.RemoveField(
            model_name='scalarboson',
            name='_parameters_1',
        ),
    ]
