# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0006_auto_20180216_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaugeboson',
            name='tenant_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='T_UUID'),
        ),
        migrations.AddField(
            model_name='lepton',
            name='tenant_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='T_UUID'),
        ),
        migrations.AddField(
            model_name='quark',
            name='tenant_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='T_UUID'),
        ),
        migrations.AddField(
            model_name='scalarboson',
            name='tenant_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='T_UUID'),
        ),
    ]
