# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20180219_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaugeboson',
            name='tenant_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="tenant's uuid"),
        ),
        migrations.AlterField(
            model_name='gaugeboson',
            name='ui_name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='lepton',
            name='tenant_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="tenant's uuid"),
        ),
        migrations.AlterField(
            model_name='lepton',
            name='ui_name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='quark',
            name='tenant_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="tenant's uuid"),
        ),
        migrations.AlterField(
            model_name='quark',
            name='ui_name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='scalarboson',
            name='tenant_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="tenant's uuid"),
        ),
        migrations.AlterField(
            model_name='scalarboson',
            name='ui_name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
    ]
